services:
  postgres:
    image: postgres:15
    container_name: crypto_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow-webserver:
    build: .
    container_name: airflow-webserver
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-webserver:8080/execution/
      AIRFLOW__API_AUTH__JWT_LEEWAY: "300"
      AIRFLOW__API_AUTH__JWT_SECRET: "crypto-pulse-jwt-secret"
      AIRFLOW__API__SECRET_KEY: "crypto-pulse-api-secret"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - ./config:/opt/airflow/config
      - ./sql:/opt/airflow/sql
    ports:
      - "8080:8080"
    command: airflow api-server

  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    depends_on:
      - postgres
      - airflow-webserver
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-webserver:8080/execution/
      AIRFLOW__API_AUTH__JWT_LEEWAY: "300"
      AIRFLOW__API_AUTH__JWT_SECRET: "crypto-pulse-jwt-secret"
      AIRFLOW__API__SECRET_KEY: "crypto-pulse-api-secret"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - ./config:/opt/airflow/config
      - ./sql:/opt/airflow/sql
    command: airflow scheduler

  airflow-dag-processor:
    build: .
    container_name: airflow-dag-processor
    depends_on:
      - postgres
      - airflow-webserver
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-webserver:8080/execution/
      AIRFLOW__API_AUTH__JWT_LEEWAY: "300"
      AIRFLOW__API_AUTH__JWT_SECRET: "crypto-pulse-jwt-secret"
      AIRFLOW__API__SECRET_KEY: "crypto-pulse-api-secret"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - ./config:/opt/airflow/config
      - ./sql:/opt/airflow/sql
    command: airflow dag-processor

volumes:
  postgres-db-volume: